name       : python3-xlib
version    : 0.15
release    : 1
source     :
    - https://pypi.python.org/packages/ef/c6/2c5999de3bb1533521f1101e8fe56fd9c266732f4d48011c7c69b29d12ae/python3-xlib-0.15.tar.gz : dc4245f3ae4aa5949c1d112ee4723901ade37a96721ba9645f2bfa56e5b383f8
license    : GPL-2.0
component  : programming.python
summary    : X11 interface for Python3
description: |
    python3-xlib is python3 version of python-xlib
build      : |
    %python3_setup   
install    : |
    %python3_install --root=%installroot% --no-compile -O0
